server:
  port: 8989
  servlet:
    context-path: /
spring:
  application:
    name: user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.189.229:3306/diancan?characterEncoding=UTF-8&useSSL=false
    username: pony
    password: 1

mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.example.demo.dao